#!/usr/bin/env php

<?php
require_once __DIR__ . '/vendor/autoload.php'; 

use Emanci\Deployer\Deployer;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new Deployer());
$app->run();
